# Generated by Django 4.1.4 on 2023-03-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authprovider', '0002_authclient_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authclient',
            name='client_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='authclient',
            name='enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='authclient',
            name='ip_adress',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='authservice',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
